# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-neliapila

# >> macros
# << macros

Summary:    Neliapila 4chan.org browser
Version:    0.9.6
Release:    1
Group:      Qt/Qt
License:    GPLv3+
BuildArch:  noarch
URL:        https://github.com/tabasku/harbour-neliapila
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-neliapila.yaml
Requires:   sailfishsilica-qt5
Requires:   libsailfishapp-launcher
Requires:   pyotherside-qml-plugin-python3-qt5
Requires:   python3-requests
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Neliapila is a app made with QML/Python3 for SailfishOS for browsing the imageboard 4chan.org

%define _binary_payload w2.xzdio

%prep
%setup -q -n %{name}-%{version}

%build

%qmake5

%make_build


%install
%qmake5_install


desktop-file-install --delete-original         --dir %{buildroot}%{_datadir}/applications                %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%defattr(0644,root,root,-)
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
